backend:
  name: github
  repo: your-username/gibulk-blog  # GANTI INI NANTI
  branch: main

media_folder: "src/images"
public_folder: "/src/images"

collections:
  - name: "blog"
    label: "Artikel Blog"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal Publikasi", name: "date", widget: "datetime" }
      - { label: "Kategori", name: "category", widget: "string", default: "Opini" }
      - { label: "Ikon (FontAwesome)", name: "icon", widget: "string", default: "feather-alt", hint: "Contoh: feather-alt, code, camera" }
      - { label: "Ringkasan", name: "excerpt", widget: "text" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }